apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: clay-technology-prod
  labels:
    app: nginx
    env: prod
    project: clay-tech
spec:
  replicas: 2 # Pour une meilleure disponibilité
  selector:
    matchLabels:
      app: nginx
      env: prod
      project: clay-tech
  template:
    metadata:
      labels:
        app: nginx
        env: prod
        project: clay-tech
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: "128Mi"
            cpu: "200m"
          requests:
            memory: "64Mi"
            cpu: "100m"
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: clay-technology-prod
  labels:
    app: nginx
    env: prod
    project: clay-tech
spec:
  type: NodePort
  selector:
    app: nginx # Doit correspondre aux labels du pod
    env: prod
    project: clay-tech
  ports:
  - name: http
    protocol: TCP
    port: 80 # Port du service interne au cluster
    targetPort: 80 # Port sur lequel le conteneur Nginx écoute
    # NodePort: (sera assigné dynamiquement par Kubernetes, entre 30000-32767, ou peut être spécifié) 